name: dt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Computación científica
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - statsmodels
  # Visualización
  - matplotlib
  - seaborn
  - pillow
  # Algoritmo evolutivo
  - deap
  # Datos
  - openpyxl
  # Jupyter
  - jupyterlab
  - ipykernel
  - nbconvert
  - nbformat
  - pip
  - pip:
      - jupyter-book
